services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=statsdb
    volumes:
      - ./pgdatastats:/var/lib/postgresql/data/

  stats-server:
    build:
      context: ./statistics
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  ewm-service:
    ports:
      - "8080:8080"
    image: busybox

  ewm-db:
    image: postgres:16.1
